dev (#12)
* wip checkStand

* got path

* wip fancy printer

* wip more printing

* wip more printing 2

* print int

* renames cb → dump

* A* but it's not quite right

* ,,

* pathfinding

* pathfinding notes

* make the step function actually step

* maybe a fix?

* steps out

* src+heurms

* flip the step output

* maybe fix?

* vector printing

* put indent in printer

* printing allocators

* wip

* todo

* multiarraylist printing

* vector inline printing

* optional pointers supported

* maybe removing the A* and making it pathfind the whole map

* pathfind the whole map instead of A*

* grid & zpool

* fixes build

* run ocln tests

* remove dst from pathfind

* creature pool

* units

* wip

* was going to swap brackets and operators

* callconv tag

* destructure specify type; next todo: c.ptr())

* wip

* power calculation

* note

* wip: prep for gui for ocln & switch to snapshot tests

* game initializes. todo: rendering & camera

* add frame time

* use opts.passIn instead of target/optimize for ocln

* rendering a full tilemap but it crashes in releasesafe

* upgrade wuffs (to a new version that disables sanitize_c) to fix ReleaseSafe crash. also makes some changes and one fix to loadimage.zig.

* TODO

* note the CI error

* maybe fix CI? workaround until zpool fixes

* notes on fixing

* maybe fix ci?

* 30->20 but we need to be much lower

* camera move

* wip serdes

* notes

* notes and art updates

* reduce map size, hide air, add a background

* add buildings & disable this test for now

* dbl notes

* dbl progress

* dbl notes

* remove buildings for now

* grid now scales to multiple dimensions

* vec.by2i32

* notes about what data to store, implement (materials,tile_flags)

* wip wires, fix test

* wires are working it seems

* .

* pressure simulation. we will need to spread it over multiple ticks somehow, this isn't sustainable

* remove intrinsic from the printing of outgoing

* remove the y info as we don't use it

* ?

* allow negative? it seems to work

* add some more water and air. now the bottom tile is receiving 20100kN (two water tiles + one air tile)

* generate the graph from a grid

* note

* confirmed that this scenerio works

* note

* notes

* notes

* switch from a grid to a map for coordinate to wires. it's a little bit slower sequential access but should be fine because how often do you need it anyway

* migrating to ConnectionLayer.1

* migrating 2

* custom printer for wires

* move all wire stuff into ConnectionLayer so we can have more types

* add a test with has_power_port

* connection_layer to its own file and fix using the wrong type names

* rename wire in connection_layer to segment to genericise

* invert can_enter to cannot_enter & use getFlag

* notes on building

* add a snapshot in pressure so it doesn't regress

* setRow impl

* confused

* so the pressure calculations don't really work yet

* value for water was extremely incorrect. by a factor of 1000. oops.

* not fully sure what we expect to see

* begin to add delete to dbl.

* wip buildings

* syncSegments works ig?

* snap fixes & canPlaceBuilding

* building place,remove maybe working?

* move snap to a new file

* prep for implementing snapshot updating

* dirname

* snapshots wip

* performReplacements wip

* snapshots are maybe complete?

* change how you call snapshots

* snapshot notes

* use addRunTest in main

* wip package-deps

* package-deps is maybe done for multi-output

* pass progress node to child. not that it does anything.

* add running package-deps to the github action

* change all versions to '0.0.0'

* updates package-deps to accept src-pkg rather than a folder to scan in

* cleanup.1 arg parsing

* cleanup.2 executing processes

* cleanup.3 moving stuff to packager

* add a compile error to detect when compression can be enabled

* cleanup.4 dependency_name map now also holds zon values

* cleanup.5 rename

* stages

* finalize fn

* preparing for std.Thread.Pool over emit

* emitFile to its own file

* remove the arena from emitFile

* prep for Thread.Pool

* multithread emit

* delete global cache dir when done

* cleanup progress node

* note about progress_node

* cleanup.6 some renames

* cleanup.7 moving some stuff into a context struct

* remove this comment

* delete dep-list.zig, update stages comment

* package-deps todo notes

* rename

* update_dependency_urls flag

* fixes

* another fix

* wip

* oops

* notes

* preserve lazy

* will be nice to run this. can't yet because of the issues.

* upgrade tracy

* ,,

* add another command

* switch to .tar.gz compression

* verbose-compression flag

* switch to tryEat

* simplify cli maybe

* update the bundle command in main yml

* the command we will run

* fix command

* migrate download urls

* Revert "migrate download urls"

This reverts commit ecc3232ed3f721b2be33f2f384835e0b99a5e8c8.

* failed because it's generating the tar with windows paths instead of posix paths

* reminder

* don't put windows paths in the tar file

* fix last commit

* migrate download urls v2, posix paths edition

* significantly reduce input latency - wait for the back buffer view to be available before collecting input

* add a rolling averager

* enable drawing while resizing the window

* wip display/1:30

* reorganize the wires in the image

* wires rendering

* render in the right order

* one port per tile rule

* wip building render

* transformation matrix when {offset,scale} and rendering fixes

* initialize a transform2d from two rects

* generator

* add a multiply fn

* serdes wip

* power outlet, lamp / 11:45

* wire calculations on grid

* wire calculations. though it seems to have outputted the wrong number (5 instead of 10)

* production-consumption matching / 1:30

* validate ser+des on update

* prep ser/des validation

* starting to work on ser/des

* more ser/des progress

* wip ser/des

* dbl get function implemented

* mapping name

* handle types

* notes

* add grid

* infer args from the filter

* include limit in Mapping() constructor

* note on serialization

* insert functions, though I'm not sure what to do about order yet

* Grid.set

* note

* begin

* fix compile

* serdes wip

* mode.in(), mode.out()

* mode.Value(), mode.Extra()

* switch() -> helper fns

* ser/des non/¢ents

* wip deletesegment

* names in sd

* readable serializer /4

* wip: add shell.nix

* fix test

* shell note

* shell.nix working now

* web fix?

* switch serialize to use a *std.Io.Writer

* deserialize -> *Reader & add diagnostic to ser/des

* switch init to ser/des validated

* dbl computed?

* value2,slice2 ser/des

* migrate fully to value2/slice2

* remove unused version for now

* fixes the type breakdown impl

* remove the why impl and also add name

* use getAstNode rather than handling zig ast directly

* migrate package-deps to 0.16 though it isn't working perfectly. it often hits an error:
error: unable to rename temporary directory C:\Users\pfg\Dev\Node\blockeditor\zig-pkg\.tmp-0a162934a0a254ba into package cache directory C:\Users\pfg\Dev\Node\blockeditor\zig-pkg\freetype-0.0.0-YcsF6UxJcwAbebb9jnWU-qz9ihJ32HEH9cbtYBpCBkHP: FileBusy
error: zig_env_proc_term .{ .exited = 1 }
error: emitFileInternal failed: Errored

* notes

* wip qxc

* wip mcfunction emit blockeditor

* fix(maybe) the comptime env stuff

* actually generated a datapack

* mcfunction function calling function

* mcfunction std.mc.runCommand

* mc: mark as ref rather than value, because values are different

* ,,

* mc notes

* ct notes

* ct notes?

* ct notes

* something like this?

* add fingerprint for 3ds

* notes

* migrate types to a type class, delete ct stuff

* on comptemp

* notes

* ct notes

* query vs list

* making mc a normal language = yikes

* mcyikes

* yikes

* ,

* fix this extra space?

* allow double newlines